version: "3.8"
services:
  bot:
    build: .
    container_name: buddy-bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    command: npx nodemon --legacy-watch buddy-bot.js